### ISSUE TITLE
Director supervisor script should not run when director is disabled

### ISSUE THREAD

**Issue by silverwind** [jjethwa/icinga2#284]
With `ICINGA2_FEATURE_DIRECTOR=0` and `DIRECTOR_KICKSTART=0`, the director module is disabled but there is still an attempt to run `/etc/supervisor/conf.d/director`, resulting in this error 20 seconds after service startup:

````
ERROR: There is no such module or command: 'director'

USAGE: icingacli [module] <command> [action] [options]
````

Deleting `/etc/supervisor/conf.d/director` solves the issue.

**Comment by jjethwa** [comment]
Hi @silverwind 

Thanks so much for the report, I totally missed that case hehe.  Fix committed, and latest is being built.  It should be available in the next 15-30 minutes 😃

**Comment by jjethwa** [comment]
jordan/icinga2:2.13.2 and jordan/icinga2:latest are available with the fix.  If it tests OK for you, please close the ticket.  Thanks again 👍

**Comment by silverwind** [comment]
Did unfortunately not work, `/etc/supervisor/conf.d/director.conf` still existed, but https://github.com/jjethwa/icinga2/pull/285 should fix it.

**Comment by silverwind** [comment]
Oh, and sorry, it was my bad, I mentioned the wrong filename in OP :)

**Comment by jjethwa** [comment]
NP and thanks for the PR 😄

**Comment by jjethwa** [comment]
New images are pushed, thanks again 👍

**Comment by silverwind** [comment]
Can confirm, error is gone. Thanks!
